Add sign-in page
vanGe1ion/mfm-front pull request #2
Opened 2022-03-01 14:56 UTC by vanGe1ion

Add sign-in page with react-router-dom, localStorage and context support

2022-03-02 07:52 UTC, Isidora25 requested changes

2022-03-02 07:52 UTC, Isidora25 commented on src/components/LoginForm.tsx
> +    <form className="h-full flex flex-col justify-around text-center p-5">
из [ТЗ](https://docs.google.com/document/d/1vjzW-vISMYInYgLqV3liMXnJPQnWji64fVcgjN3-G6Q/edit): _ВНИМАНИЕ: Здесь и далее для верстки следует использовать готовый CSS framework (Tailwind), **CSS стоит реализовывать сразу с Styled Components**_

2022-03-02 07:52 UTC, Isidora25 commented on src/components/LoginForm.tsx
> +        <ButtonFull onClick={buttonSubmitHandler}>Confirm</ButtonFull>
Не нужно навешивать обработчик на каждый инпут формы, чтобы детектить их изменения. 
Получается, что сейчас на каждую введенную букву в инпуте у компонента меняется стейт. Соответственно, компонент ререндерится. 
Поэтому здесь стоит использовать крайне полезный функционал html форм - form submit 
https://developer.mozilla.org/ru/docs/Web/API/HTMLFormElement/submit

Есть пара основных пакетов, делающее работу с формами в реакт проще  - https://final-form.org/react, https://formik.org/ Рекомендую посмотреть 

Правильное использование формы позволит тебе избавиться от кучи ненужных стейтов и обработчиков правильно обрабатывать ошибки

2022-03-02 07:52 UTC, Isidora25 commented on src/components/LoginForm.tsx
> +          setLoginClasses(addAlertClass);
Чем принципиально отличается стилизация поля инпута для логина и пароля? Здесь определенно ты совершаешь лишние телодвижения, чтобы стилизовать инпут с ошибкой. 
Используй один styled component для инпутов логина и пароля и тогда стили нужно будет применять только к одному элементу. У styled compщnents есть очень удобный функционал пропсов. Используй его https://styled-components.com/docs/basics#passed-props

2022-03-02 07:52 UTC, Isidora25 commented on src/components/LoginFormGroup.tsx
> +const LoginFormGroup: FC = ({children}) => {
https://styled-components.com/
И тогда не придется создавать отдельный компонент только для дива со стилями

2022-03-02 07:52 UTC, Isidora25 commented on src/components/LoginForm.tsx
> +        default: {
switch case для всего двух вариантов условия? 
Используй что-нибудь попроще

2022-03-02 07:52 UTC, Isidora25 commented on src/components/UI/ButtonFull.tsx
> +  border: 3px solid #0484c7;
Styled Components + Tailwind [1]

2022-03-02 07:52 UTC, Isidora25 commented on src/components/UI/Label.tsx
> +const Label = styled.label`
см [1]

2022-03-02 07:52 UTC, Isidora25 commented on src/components/UI/ButtonFull.tsx
> +import styled from "styled-components";
Здесь нет нуждны в расщирении файла `tsx` 
https://ru.reactjs.org/docs/introducing-jsx.html

2022-03-02 07:52 UTC, Isidora25 commented on src/components/UI/LabelError.tsx
> +const LabelError = styled(Label)`
см [1]

2022-03-02 07:52 UTC, Isidora25 commented on src/components/UI/TextInput.tsx
> +  type: "text",
см [2]

2022-03-02 07:52 UTC, Isidora25 commented on src/components/UserContextProvirer.tsx
> +    let approvedUser: string | null = localStorage.getItem("currentUserId");
Если `approvedUser` нигде не изменяется по коду, для чего использовать let?

2022-03-02 07:52 UTC, Isidora25 commented on src/components/routers/UnauthRouter.tsx
> +      <Route path="/sign_in" exact>
см [3]

2022-03-02 07:52 UTC, Isidora25 commented on src/context/userContext.ts
> +  approveUser: () => {},
А почему здесь функция возвращает пустой объект, если в useUserAuth она описана с типом возврата void?

2022-03-02 07:52 UTC, Isidora25 commented on src/pages/LoginPage.tsx
> +    <div className="min-h-screen min-w-full bg-sky-100 flex flex-col">
Styled Components

2022-03-02 07:52 UTC, Isidora25 commented on src/utils.ts
> +  return localStorage.getItem("login") === login &&
(localStorage.getItem("login") === login)  === true 

Возвращать явно true нет необходимости

2022-03-02 12:26 UTC, vanGe1ion commented on src/context/userContext.ts
> +  approveUser: () => {},
а как описать дефолтный объект с пустой функцией? он должен реализовывать интерфейс

2022-03-02 13:01 UTC, vanGe1ion commented on src/components/routers/AuthRouter.tsx
> +      <Route path="/main" exact>
я предполагаю, что в случае неавторизованного перехода  мы имеем доступ только к странице логина в случае же авторизованного - имеем доступ к основной странице и не должны иметь доступ к странице логина

2022-03-02 13:04 UTC, vanGe1ion commented on src/context/userContext.ts
> +  approveUser: () => {},
как описать пустую функцию для дефолтного объекта, чтобы он реализовывал указанный интерфейс?

2022-03-09 12:41 UTC, Isidora25 requested changes
Стоит вернуть react final form
Библиотека очень популярная и с ней нужно уметь работать

2022-03-09 12:41 UTC, Isidora25 commented on src/components/RoterSwitcher.tsx
> +      {currentUser === null ? <UnauthRouter /> : <AuthRouter />}
а если currentUser === 'undefined'?

2022-03-09 12:41 UTC, Isidora25 commented on src/App.tsx
> +// import UserContextProvirer from "./components/UserContextProvirer";
Не оставляй в коде закомментированные строки

2022-03-09 12:41 UTC, Isidora25 commented on src/components/LoginForm/LoginForm.style.ts
> +// interface I
Не оставляй в коде закомментированные строки

2022-03-09 12:41 UTC, Isidora25 commented on src/components/LoginForm/LoginForm.tsx
> +    console.log(event.currentTarget.elements);
Логи в коде тоже не нужно оставлять, для пользователей они никакой пользы не несут

2022-03-09 12:41 UTC, Isidora25 commented on src/components/LoginForm/LoginForm.tsx
> +        <LabelError>{null}</LabelError>
null?

2022-03-09 12:41 UTC, Isidora25 commented on src/components/UI/FormInput.ts
> +  padding: ${({ size }) => size ?? "4px"};
Почему отступы завязаны на size всего инпута? 
если size = 150px то и отступы будут 150px?

2022-03-09 12:41 UTC, Isidora25 commented on src/pages/MainPage/MainPage.style.ts
> +import styled from "styled-components";
Если в файле ничего нет, то его следует удалить из проекта

2022-03-09 12:41 UTC, Isidora25 commented on src/pages/MainPage/MainPage.tsx
> +import {  } from "./MainPage.style";
Импорт чего здесь происходит?

2022-03-09 12:41 UTC, Isidora25 commented on src/components/UI/Button.tsx
> +const Button = styled.button`
Файлы стилей не нуждаются в расширении tsx

2022-03-09 12:41 UTC, Isidora25 commented on src/components/FormInput.tsx
> +      <Label htmlFor={id}>{id[0].toUpperCase() + id.slice(1)}</Label>
А у тебя не может быть в форме двух полей с одинаковыми лейблами? 
  id != label 
  Зачем так извращаться, лучше завести отдельный проп для label и отдельный для id

2022-03-09 12:41 UTC, Isidora25 commented on src/components/LoginForm/LoginForm.tsx
> +        callback();
почему бы здесь просто не вызвать: 
```
 approveUser(login);
 history.replace("/main");
```
?

Коллбэк - ненужное усложнение

2022-03-09 12:41 UTC, Isidora25 commented on src/components/LoginForm/LoginForm.tsx
> +    setSignInError((prev) => [...prev, newError]);
React Final Form позволяет удобно работать с ошибками формы. И при сабмите, и просто при вводе значений в форму. 
Для чего изобретать велосипед?

2022-03-09 12:41 UTC, Isidora25 commented on src/components/UI/Label.tsx
> +  ${({ type }) => (type === "error" ? "font-style: italic;  color: red;" : "")};
Лучше стили для ошибки вынести это отдельным миксином https://styled-components.com/docs/api#css

2022-03-09 12:41 UTC, Isidora25 commented on src/pages/MainPage/MainPage.tsx
> +      <Button size="6px" onClick={logoutButtonHandler}>
size чего? Кнопки? тогда почему такая маленькая, 6px?
Переменная названа не однозначно

2022-03-09 13:42 UTC, khmm12 commented on src/pages/MainPage/MainPage.tsx
> +      <Button size="6px" onClick={logoutButtonHandler}>
My 2 coins. There is a common convention related to properties and handlers naming.

```
onClick={handleLogoutClick}
```

2022-03-09 13:45 UTC, khmm12 commented on src/pages/LoginPage/LoginPage.tsx
> +import logo from "../../media/logo190.png";
I'd avoid "trash" folders. It's better to keep such things near to a component.

e.g.
```
pages/LoginPage/index.tsx
pages/LoginPage/logo.png
```

2022-03-15 13:23 UTC, merged