Main page with movie row list PR1
vanGe1ion/mfm-front pull request #5
Opened 2022-04-08 10:15 UTC by vanGe1ion

2022-04-08 12:32 UTC, Isidora25 requested changes

2022-04-08 12:32 UTC, Isidora25 commented on src/components/MovieRowItem/MovieRowItem.tsx
> +        LSAPIRemoveFavouriteMovie(movie.id!)
Опять, почему в функции установки нового стейта происходят левые вещи?

2022-04-08 12:32 UTC, Isidora25 commented on src/components/MovieRowItem/MovieRowItem.tsx
> +        LSAPIRemoveFavouriteMovie(movie.id!)
movie.id**!** -  а это для чего?

2022-04-08 12:32 UTC, Isidora25 commented on src/components/MovieRowItem/MovieRowItem.tsx
> +const MovieRowItem: FC<IMovieListItemProps> = ({ movie, setMovies, index }) => {
Используй деструктуризацию для movie

2022-04-08 12:32 UTC, Isidora25 commented on src/components/MovieRowItem/MovieRowItem.tsx
> +            <YearSpan>({movie.releaseDate?.split("-")[0]})</YearSpan>
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/getFullYear

2022-04-08 12:32 UTC, Isidora25 commented on src/components/MoviesList/MoviesList.tsx
> +  const ListItem = view === "row" ? MovieRowItem : MovieBlockItem;
А вот если бы переменная view была  типа boolean это было бы все гораздо проще

2022-04-08 12:32 UTC, Isidora25 commented on src/pages/MainPage/MainPage.tsx
> +  const [view, setView] = useState<TMovieView>('row');
используй boolean для view

2022-04-08 12:37 UTC, vanGe1ion commented on src/components/GenresPanel/GenresPanel.tsx
> +  const GenreClickHandler = (genreIdx: number): void => {
очепятка. принято

2022-04-08 12:41 UTC, vanGe1ion commented on src/components/GenresPanel/GenresPanel.tsx
> +        {genres.map((genre, index) => {
есть

2022-04-08 13:53 UTC, vanGe1ion commented on src/components/GenresPanel/style.ts
> +  ${tw`flex flex-row m-5 p-1 pt-2 border-4 border-blue-500 rounded-2xl`}
хорошо, тогда  px-1 pb-1 pt-2

2022-04-08 13:55 UTC, vanGe1ion commented on src/components/MovieControl/MovieControl.tsx
> +import IconedButton from "../IconedButton";
к сожалению svg платные

2022-04-08 14:04 UTC, vanGe1ion commented on src/components/GenresPanel/GenresPanel.tsx
> +              onClick={() => GenreClickHandler(index)}
решено

2022-04-08 14:04 UTC, vanGe1ion commented on src/components/GenresPanel/GenresPanel.tsx
> +      };
разобрались

2022-04-08 14:04 UTC, vanGe1ion commented on src/components/GenresPanel/GenresPanel.tsx
> +      LSAPISetFavouriteGenres(favoritesIdx);
убрал

2022-04-08 14:07 UTC, vanGe1ion commented on src/components/GenresPanel/style.ts
> +  ${tw`bg-blue-200 px-3 relative -top-6 left-4 whitespace-nowrap h-5`}
исправил

2022-04-11 09:10 UTC, Isidora25 approved these changes

2022-04-11 09:12 UTC, merged