Release Movie Block View PR
vanGe1ion/mfm-front pull request #6
Opened 2022-04-11 12:39 UTC by vanGe1ion

2022-04-11 14:26 UTC, Isidora25 requested changes

2022-04-11 14:26 UTC, Isidora25 commented on src/components/MovieBlockItem/MovieBlockItem.tsx
> +  const releaseYear = new Date(releaseDate!).getFullYear();
Кажется, я уже где-то такое видела 
Попробуй выделить общие блоки из блочного компонента и из компонента для списка

2022-04-12 09:22 UTC, vanGe1ion commented on src/components/MovieBlockItem/MovieBlockItem.tsx
> +  const releaseYear = new Date(releaseDate!).getFullYear();
поправил

2022-04-12 10:30 UTC, Isidora25 approved these changes

2022-04-12 11:14 UTC, merged